logging:
  level.root: WARN
  level.no: ${LOG_LEVEL:DEBUG}

spring:
  data.mongodb.database: concept-catalogue
  data.mongodb.uri: mongodb://${MONGO_USERNAME:admin}:${MONGO_PASSWORD:admin}@${MONGO_HOST:mongodb:27017}/?authSource=admin&authMechanism=SCRAM-SHA-1&serverSelectionTimeoutMS=2000

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: ${RABBIT_USERNAME}
    password: ${RABBIT_PASSWORD}
    template:
      routing-key: 'concept.publisher.HarvestTrigger'
      exchange: 'harvests'

application:
  collectionBaseUri: ${COLLECTION_BASE_URI:https://registrering-begrep.fellesdatakatalog.brreg.no}

security:
  oauth2:
    resource:
      id: concept-catalogue
      jwk.key-set-uri: ${JWK_KEY_SET_URI:http://sso:8084/auth/realms/fdk/protocol/openid-connect/certs}
---

spring:
  profiles: develop,test,unit-integration
  data.mongodb.uri: mongodb://${MONGO_USERNAME:admin}:${MONGO_PASSWORD:admin}@${MONGO_HOST:localhost:27017}/?authSource=admin&authMechanism=SCRAM-SHA-1&serverSelectionTimeoutMS=2000

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: admin

logging:
  level:
    org.springframework.security: DEBUG
    no.brreg: DEBUG

server:
  port: 8201

security:
  oauth2:
    resource:
      id: concept-catalogue
      jwk.key-set-uri: http://localhost:8084/jwk