spring:
  datasource:
    url: ${FDK_CONCEPT_CATALOGUE_SQL_JDBC_CONNECTION:jdbc:postgresql://localhost:5432/postgres?currentSchema=conceptregistration}
    username: ${FDK_CONCEPT_CATALOGUE_SQL_USERNAME}
    password: ${FDK_CONCEPT_CATALOGUE_SQL_PASSWORD}

---

spring:
  profiles: develop,unit-integration
server:
  port: 8101