name: Run tests

on:
  push:
    branches-ignore:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Build Docker image
        run: docker build . -q -t eu.gcr.io/fdk-infra/concept-catalogue:latest
      - name: Run tests
        run: mvn verify